### ISSUE TITLE
missing character from AlternativeIterator

### ISSUE THREAD

**Issue by teeshop** [teeshop/rexgen#12]
Hi

I think this is a bug:

$ rexgen [pP][aA][sS][sS]|rexgen -f - "(?i:r|d|t|f)\0"
rpass
Rpass
dpass
Dpass
tpass
Tpass
fpass
Fpass
Pass
dPass
DPass
tPass
TPass
fPass
FPass
pAss
dpAss
DpAss
tpAss
TpAss
fpAss
FpAss
PAss
dPAss
DPAss
tPAss
TPAss
fPAss
FPAss
paSs
dpaSs
DpaSs
tpaSs
TpaSs
fpaSs
FpaSs
PaSs
dPaSs
DPaSs
tPaSs
TPaSs
fPaSs
FPaSs
pASs
dpASs
DpASs
tpASs
TpASs
fpASs
FpASs
PASs
dPASs
DPASs
tPASs
TPASs
fPASs
FPASs
pasS
dpasS
DpasS
tpasS
TpasS
fpasS
FpasS
PasS
dPasS
DPasS
tPasS
TPasS
fPasS
FPasS
pAsS
dpAsS
DpAsS
tpAsS
TpAsS
fpAsS
FpAsS
PAsS
dPAsS
DPAsS
tPAsS
TPAsS
fPAsS
FPAsS
paSS
dpaSS
DpaSS
tpaSS
TpaSS
fpaSS
FpaSS
PaSS
dPaSS
DPaSS
tPaSS
TPaSS
fPaSS
FPaSS
pASS
dpASS
DpASS
tpASS
TpASS
fpASS
FpASS
PASS
dPASS
DPASS
tPASS
TPASS
fPASS
FPASS

The first string (in this case "r") is printed only for "pass", for
other combination is ignored or empty.

Bests

**Comment by wrzomar** [comment]
There is a difference between rexgen and some program that is using librexgen library. This command:
$ rexgen [pP][aA]|rexgen -f - "(?i:y|n)\0(?i:y|n)"
generates this output:
ypay
Ypay
npay
Npay
paY
npaY
NpaY
pan
npan
Npan
paN
npaN
NpaN
Pa
nPa
NPa
Pan
nPan
NPan
PaN
nPaN
NPaN
pA
npA
NpA
pAn
npAn
NpAn
pAN
npAN
NpAN
PA
nPA
NPA
PAn
nPAn
NPAn
PAN
nPAN
NPAN

but this program that is using librexgen for identical regular expression generates this output:
ypay
Ypay
npay
Npay
Pay
nPay
NPay
pAy
npAy
NpAy
PAy
nPAy
NPAy
paY
npaY
NpaY
PaY
nPaY
NPaY
pAY
npAY
NpAY
PAY
nPAY
NPAY
pan
npan
Npan
Pan
nPan
NPan
pAn
npAn
NpAn
PAn
nPAn
NPAn
paN
npaN
NpaN
PaN
nPaN
NPaN
pAN
npAN
NpAN
PAN
nPAN
NPAN

So I think there are two problems of missing string from AlternativeIterator in rexgen - one for prefix and another for postfix whereas in librexgen the missing string is only for prefix. I've used single letter examples because they are shorter but if you replace them with string than you will see that this problem exist for entire strings. I wasn't trying with two \0 in one expression, so I don't know what happens then.

**Comment by wrzomar** [comment]
One more thing (the last, I hope). Rexgen without pipe reference (\0):
$ rexgen "(?i:y|n)[pP][aA](?i:y|n)"
ypay
Ypay
npay
Npay
Pay
nPay
NPay
pAy
npAy
NpAy
PAy
nPAy
NPAy
paY
npaY
NpaY
PaY
nPaY
NPaY
pAY
npAY
NpAY
PAY
nPAY
NPAY
pan
npan
Npan
Pan
nPan
NPan
pAn
npAn
NpAn
PAn
nPAn
NPAn
paN
npaN
NpaN
PaN
nPaN
NPaN
pAN
npAN
NpAN
PAN
nPAN
NPAN

This is identical output as from previous JtR example (49 lines). JtR generates the same output if you run it with --regex="(?i:y|n)[pP][aA](?i:y|n)" --stdout options (49 lines without pipe reference). I hope it is helpful.

**Comment by teeshop** [comment]
a better test case, because it is shorter:
```
$ rexgen '(?i:xy)' | rexgen -f - '(?i:a|b)-\0'
a-xy
A-xy
b-xy
B-xy
-Xy
b-Xy
B-Xy
-XY
b-XY
B-XY
-xY
b-xY
B-xY
```

**Comment by teeshop** [comment]
I think I fixed the issue in SHA: 21291c804710b26da1a5a9bca7425200458333ae

can you please give it a try?

**Comment by wrzomar** [comment]
It's working in rexgen, but I can't test it with JtR, because it's not building with this version of librexgen. I don't have previous version of librexgen (because I pulled new one), but I don't know if it's librexgen fault or JtR's. This is output of make:
regex.c: In function ‘do_regex_crack_as_rules’:
regex.c:107:2: error: unknown type name ‘c_iterator_ptr’
regex.c:107:24: warning: initialization makes integer from pointer without a cast [enabled by default]
regex.c:162:2: warning: implicit declaration of function ‘c_regex_iterator_cb’ [-Wimplicit-function-declaration]
regex.c:167:2: warning: implicit declaration of function ‘c_iterator_next’ [-Wimplicit-function-declaration]
regex.c:168:3: warning: implicit declaration of function ‘c_iterator_value’ [-Wimplicit-function-declaration]
regex.c:174:5: warning: implicit declaration of function ‘c_iterator_delete’ [-Wimplicit-function-declaration]
regex.c: In function ‘do_regex_crack’:
regex.c:186:2: error: unknown type name ‘c_iterator_ptr’
regex.c:186:24: warning: initialization makes integer from pointer without a cast [enabled by default]
make[1]: *** [regex.o] Błąd 1
make: *** [default] Błąd 2

I'll post it on john-users list and see what happens.

Thanks for help.

Best Regards,
wrzomar

**Comment by teeshop** [comment]
I will have a look at this

**Comment by teeshop** [comment]
please apply the following patch:
```
diff --git a/src/regex.h b/src/regex.h
index b2c7199..afa3a2c 100644
--- a/src/regex.h
+++ b/src/regex.h
@@ -32,7 +32,8 @@
 		/* librexgen fux this up for Win32 builds. We have coded JtR to use sprintf_s, and not _snprintf. They ARE different */
 		#undef  snprintf
 	#endif
-  #include <librexgen/api/c/librexgen.h>
+  #include <librexgen/c/librexgen.h>
+  #include <librexgen/c/iterator.h>
 	#if defined(_WIN32)
 		/* librexgen fux this up for Win32 builds. We have coded JtR to use sprintf_s, and not _snprintf. They ARE different */
 		#undef  snprintf
```

**Comment by magnumripper** [comment]
@teeshop thanks. Our latest code already had the path right so I just added iterator.h. @wrzomar latest bleeding-jumbo is patched now, please try it out and report back.

**Comment by wrzomar** [comment]
I've successfully built bleeding-jumbo with librexgen support. Thanks.
